### Variables for different environments
@baseUrl = http://localhost:3000
# @baseUrl = https://trading-admin-jade.vercel.app
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
@verificationToken = 

### Login Customer (Signin)
# @name login
POST {{baseUrl}}/api/v1/customer/signin
Content-Type: application/json

{
    "email": "sainyi@gmail.com",
    "password": "sainyinyitun"
}

### Get Working (Reference)
GET {{baseUrl}}/api/v1/working

### Update authToken with login response
@authToken = {{login.response.body.token}}

### Sign Up Customer
POST {{baseUrl}}/api/v1/customer/signup
Content-Type: application/json

{
    "name": "sainyi",
    "email": "sainyi@gmail.com",
    "password": "sainyi",
    "fundPassword": "123456",
    "phoneNumber": "1234567890",
    "referCode": "CODE"
}

### Verify Token
POST {{baseUrl}}/api/v1/customer/verify-token
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Get All Customer Info
GET {{baseUrl}}/api/v1/customer
Content-Type: application/json

### Activate Order Plan
POST {{baseUrl}}/api/v1/customer/activate-order-plan
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Get Order Plan
GET {{baseUrl}}/api/v1/customer/order-plan
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Start Order
POST {{baseUrl}}/api/v1/customer/start-order
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "order_id": "ORD016I3CG"
}


### Get Orders (excluding NOT_START)
GET {{baseUrl}}/api/v1/customer/orders
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

### Confirm Order
POST {{baseUrl}}/api/v1/customer/confirm-order
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "order_id": "ORD01B8Y75"
}

### Complete Order
POST {{baseUrl}}/api/v1/customer/complete-order
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "order_id": "ORD01B8Y75"
}


### Send Message
POST {{baseUrl}}/api/v1/customer/chat/message
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "text": "Hello, how are you?",
    "img": ""
}
