### Variables for different environments
@baseUrl = http://localhost:3000
# @baseUrl = https://trading-admin-jade.vercel.app
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
@verificationToken = 

### Login Customer (Signin)
# @name login
POST {{baseUrl}}/api/v1/customer/signin
Content-Type: application/json

{
    "email": "sainyi@gmail.com",
    "password": "sainyinyitun"
}

### Get Working (Reference)
GET {{baseUrl}}/api/v1/working

### Update authToken with login response
@authToken = {{login.response.body.token}}

### Sign Up Customer
POST {{baseUrl}}/api/v1/customer/signup
Content-Type: application/json

{
    "name": "sainyi",
    "email": "sainyi@gmail.com",
    "password": "sainyi",
    "fundPassword": "123456",
    "phoneNumber": "1234567890",
    "referCode": "CODE"
}

### Verify Token
POST {{baseUrl}}/api/v1/customer/verify-token
Content-Type: application/json
Authorization: Bearer {{authToken}}